name: Push Desktop File to GitHub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy Desktop File
        run: cp C:/Users/svelpuri/Desktop/prime.java git-push-demo/.github/workflows/push-main.yml
      - name: Commit Changes
        run: |
         
          git add .
          git commit -m "Add desktop file"
      - name: Push Changes
        uses: ad-m/github-push-action@master
     
