name: Java Workflow with Cron Job
on:
  schedule:
    - cron: "54 16 * * *"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile Java file
      run: javac /C:/Users/svelpuri/Desktop/prime.java
    - name: Run Java program
      run: java -cp /C:/Users/svelpuri/Desktop/prime
         
