name: Java Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile Java file
      run: javac C:/Users/svelpuri/Desktop/prime.java
    - name: Run Java program
      run: java -cp C:/Users/svelpuri/Desktop/prime
